[package]
name = "flat_serialize"
version = "0.1.0"
authors = ["Joshua Lockerman"]
edition = "2018"

[dev-dependencies]
flat_serialize_macro = {path="../flat_serialize_macro", features= ["print-generated"]}
